### ISSUE TITLE
gps not working

### ISSUE THREAD

**Issue by aexm33** [crdroidandroid/crdroid_features#99]
None of the map aps work. Cant find my location. The gps is working on everything else except map apps. Pls help

**Comment by gwolf2u** [comment]
invalid

**Comment by aexm33** [comment]
Lol what? Just closed my question no answer nothing?

**Comment by gwolf2u** [comment]
there might be a reason I did it
first of, not proper place to report and second, this is use issue caused by gapps not being installed before boot to system

**Comment by aexm33** [comment]
My man, im searching for a place to report this issue.this is the only place i found. What do you mean gaps are not installed on boot? I got NikGapps-core-arm64-13-20230418-signed installed

**Comment by gwolf2u** [comment]
you are most likely using a A/B device
now, with those devices you need to install update, reboot to recovery and reinstall gapps
issue is caused by gapps not installing proper permissions

also reporting issue is done to the proper place aka issue_tracker
https://github.com/crdroidandroid/issue_tracker/issues/new/choose

is not about being an ass or so... is just every day people not reading and replying to same question when already asked being time consuming and unproductive
https://github.com/crdroidandroid/issue_tracker/issues/59
